version: '2'
services:
  myapp:
    build:
      context: .
    ports:
      - '8000:80'
    volumes:
      - './myapp:/var/www/'
    depends_on:
      - mariadb
  mariadb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=bitnami_app
      # - MYSQL_ROOT_USERNAME=bn_app
      - MYSQL_ROOT_PASSWORD=QmWc6m5jdo
      - DB_SOCKET=/Applications/MAMP/tmp/mysql/mysql.sock
    ports:
      - "33020:3306"
