version: '3.8'

services:
  #Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: php.dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    command: >
      /bin/sh -c "composer install
      && php artisan migrate && php-fpm"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/:/usr/local/etc/php/conf.d/
      - ./nginx_logs/:/var/log/  
    ports:
      - '9000:9000'
  mysql:
    image: mysql:5.7.32
    container_name: mysql
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

